// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeXJEeSNV6hJNyPGFhV5U3Xwr7ng-IihM',
    appId: '1:944165086970:android:3dd561df74ffc08c85cb43',
    messagingSenderId: '944165086970',
    projectId: 'ambu-time',
    storageBucket: 'ambu-time.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qt5W9lOq6BEE0Bpl4mvVEjD8dcLMyJo',
    appId: '1:944165086970:ios:74a7e3cc5c17357085cb43',
    messagingSenderId: '944165086970',
    projectId: 'ambu-time',
    storageBucket: 'ambu-time.firebasestorage.app',
    androidClientId: '944165086970-dar0nb909efe4j26gkm5adnk9so7aehg.apps.googleusercontent.com',
    iosClientId: '944165086970-rdpc97eejfia2uide4t0p2n0he988uki.apps.googleusercontent.com',
    iosBundleId: 'com.onnoff.ambutime',
  );

}