/// Codes de gratuité AmbuTime (Premium à vie). Générés le 21/07/2026.
/// Insensible à la casse et aux espaces (cf. PremiumService.activerAvecCode).
/// Les mêmes codes fonctionnent sur Android et iOS (code Flutter partagé).
class PremiumCodes {
  static const Set<String> valides = {
    'AMBU-PRO-VZLAJW',
    'AMBU-PRO-AM27LB',
    'AMBU-PRO-KQPD5S',
    'AMBU-PRO-KXPRRU',
    'AMBU-PRO-PVNN32',
    'AMBU-PRO-493YMV',
    'AMBU-PRO-QNKNB3',
    'AMBU-PRO-9JPJSW',
    'AMBU-PRO-9PXSZU',
    'AMBU-PRO-QC86WS',
    'AMBU-PRO-XTMBMQ',
    'AMBU-PRO-GMCZU5',
    'AMBU-PRO-LNNHSM',
    'AMBU-PRO-YJ7PTX',
    'AMBU-PRO-TK28D9',
    'AMBU-PRO-2CWVSS',
    'AMBU-PRO-JBK5QP',
    'AMBU-PRO-BT7E3X',
    'AMBU-PRO-D5FP97',
    'AMBU-PRO-ZGD3CR',
    'AMBU-PRO-KCHMQY',
    'AMBU-PRO-Q2S8EB',
    'AMBU-PRO-2SP9BT',
    'AMBU-PRO-KC9NGD',
    'AMBU-PRO-XNTSSJ',
    'AMBU-PRO-ZTML59',
    'AMBU-PRO-ZCCBCM',
    'AMBU-PRO-9FVFEA',
    'AMBU-PRO-JA6SPV',
    'AMBU-PRO-Z2VPRJ',
    'AMBU-PRO-3D764T',
    'AMBU-PRO-S7WFDL',
    'AMBU-PRO-5J8HBU',
    'AMBU-PRO-PWL44F',
    'AMBU-PRO-MA6KPX',
    'AMBU-PRO-7KFYMZ',
    'AMBU-PRO-JE4KB6',
    'AMBU-PRO-3NU4Z6',
    'AMBU-PRO-X6ZAV5',
    'AMBU-PRO-HCP6HF',
    'AMBU-PRO-4ZZA2S',
    'AMBU-PRO-SW9NQS',
    'AMBU-PRO-RUELPV',
    'AMBU-PRO-SUFFYF',
    'AMBU-PRO-YPET7V',
    'AMBU-PRO-FSUAF3',
    'AMBU-PRO-4AYEDT',
    'AMBU-PRO-76728H',
    'AMBU-PRO-ESATHV',
    'AMBU-PRO-HX8QM4',
  };
}
